clear, clc, close all

rns = 0:9; % random number seeds

for i = 1:length(rns)
    [NLL(i),AIC(i)] = RecoveryTesting('real',rns(i));
end

%%
% writetable(table(...
%     rn,... %%%
%     NLL.dPrimeAndGaussianWidth,...
%     NLL.single_ssnu,...
%     NLL.single_sg,...
%     NLL.simultaneous,...
%     NLL.iterative,...
%     AIC.dPrimeAndGaussianWidth,...
%     AIC.single_ssnu,...
%     AIC.single_sg,...
%     AIC.simultaneous,...
%     AIC.iterative),...
%     ['NLL_AIC_rn',num2str(rn),... %%%
%     '_',datestr(now,'yymmdd-HHMMSS'),'.csv'])

clc
writetable(struct2table(NLL),...
    ['NLL','_',datestr(now,'yymmdd-HHMMSS'),'.csv'])

clc
writetable(struct2table(AIC),...
    ['AIC','_',datestr(now,'yymmdd-HHMMSS'),'.csv'])